name: Docker action private

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello ... action step
        uses: ./ # Uses an action in the root directory
        id: word
        with:
          who-to-greet: "e2517 Software Enginner"
      # Use the output from the `word` step
      - name: Get the output time
        run: echo "The time was ${{ steps.word.outputs.time }}"
